version: '2'
services:
  web:
    build:
      context: ../app
    image: webapp
    command: python app.py
    ports:
      - 5000
    networks:
      - net
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - net

networks:
  net:
    driver: overlay
