version: '2'
services:
  web:
    build:
      context: ../app
    image: webapp:latest
    command: python app.py
    ports:
      - 5000:5000
    links:
      - redis

  redis:
    image: redis:latest
