version: '2'
services:
  web:
    build: .
    command: python app.py
    ports:
      - 5000
    volumes:
      - .:/code
    networks:
      - front
      - back
    links:
      - redis

  redis:
    image: redis:latest
    networks:
      - back

  lb:
    image: dockercloud/haproxy
    ports:
      - 5000:80
    links:
      - web
    networks:
      - front
      - back
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  front:
    driver: bridge
  back:
    driver: bridge
