version: '2'
services:
  lb:
    image: dockercloud/haproxy
    ports:
      - 5000:80
    links:
      - web
    networks:
      - front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  web:
    build:
      context: ../app
    image: webapp
    command: python app.py
    ports:
      - 5000
    networks:
      - front
      - back
    links:
      - redis

  redis:
    image: redis:latest
    networks:
      - back

networks:
  front:
    driver: overlay
  back:
    driver: overlay
